services:
  postgres:
    image: postgres:16-alpine
    container_name: dunwell-db
    restart: unless-stopped
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: dunwell
      POSTGRES_PASSWORD: dunwell_pass
      POSTGRES_DB: dunwell_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
