services:
  postgres:
    image: postgres:16-alpine
    container_name: mapestate-db
    restart: unless-stopped
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: mapestate
      POSTGRES_PASSWORD: mapestate_pass
      POSTGRES_DB: mapestate_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  mapestate_uploads:
